### ISSUE TITLE
RuntimeError with test_pretained.sh 

### ISSUE THREAD

**Issue by KevinDonnot** [mtli/PhotoSketch#10]
Hello,

I can't run the` test_pretained.sh `script after (apparent) correct Conda env configuration. (MacOS 10.14.6). After setting the dataDir in the test_pretained script, I get this error : 

`Traceback (most recent call last):
  File "test_pretrained.py", line 29, in <module>
    main()
  File "test_pretrained.py", line 21, in main
    for i, data in enumerate(dataset):
  File "/Users/kevin/Documents/PhotoSketch/data/custom_dataset_data_loader.py", line 41, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "/Users/kevin/Documents/miniconda2/envs/sketch/lib/python3.6/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99`

I suspect a PyTorch related error: 

After trying to reinstall the Conda env, I noticed this output:
`Installing collected packages: torch, Pillow, torchvision, dominate, pyzmq, jsonpointer, jsonpatch, tornado, websocket-client, torchfile, idna, chardet, urllib3, requests, visdom
  Found existing installation: torch 0.4.1
    Uninstalling torch-0.4.1:
      Successfully uninstalled torch-0.4.1
Successfully installed Pillow-5.0.0 chardet-3.0.4 dominate-2.4.0 idna-2.8 jsonpatch-1.24 jsonpointer-2.0 pyzmq-18.1.0 requests-2.22.0 torch-1.3.0 torchfile-0.1.0 torchvision-0.4.1 tornado-6.0.3 urllib3-1.25.6 visdom-0.1.8.9 websocket-client-0.56.0`

When I launch `python -c "import torch; print(torch.__version__)"` in the Terminal and the "sketch" Conda environment, I got `1.3.0` which seems different from the 0.4 version expected in the environment file...)

Seems that the env file does not force torch version and Conda auto-update to 1.3.0 which might cause trouble. Any clue on this one?

Thank for for your further help!

**Comment by KevinDonnot** [comment]
Solved! Solution is to downgrade PyTorch to 1.0.1!
